Create database da_project;

use da_project;

SELECT * from customer_behavior limit 10;

-- I will take 10 project questions, this will helps to know some valuable insights for this Project using SQL queries.
 
-- Q1. What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as total_revenue from customer_behavior
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select avg(purchase_amount) from customer_behavior;
-- Average purchase amount is 59.76
SELECT customer_id, purchase_amount from customer_behavior
where discount_applied = 'Yes' and (select avg(purchase_amount) from customer_behavior)<=purchase_amount
limit 10;

-- Q3. Which are the top 5 products with the heighest average review rating?
SELECT item_purchased, round(avg(review_rating), 2) as rating from customer_behavior
GROUP BY item_purchased
order by rating DESC
limit 5;

-- Q4. Compare the average purchase amount between the standard and Express shipping.
SELECT shipping_type, avg(purchase_amount) from customer_behavior
GROUP BY shipping_type
HAVING shipping_type in ('Express', 'Standard');

-- Q5. Do Subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status, count(customer_id) as total_customers, avg(purchase_amount) as avg_spend, 
sum(purchase_amount) as total_spend from customer_behavior
GROUP BY subscription_status;

-- Q6. Which 5 products have the heighest percentage of purchases with discounts applied?
SELECT item_purchased, round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*), 2) as discount_rate from customer_behavior
group by item_purchased
order by discount_rate DESC
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
 SELECT case 
 when previous_purchases=1 then 'New'
 when previous_purchases BETWEEN 2 and 10 then 'Returning'
 when previous_purchases>=10 then 'Loyal'
 end as segment_customers,
 count(previous_purchases) as total_counts from customer_behavior
 group by segment_customers;

-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (SELECT item_purchased, category, count(customer_id) as total, 
ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(customer_id) DESC) as item_Rank from customer_behavior
GROUP BY category, item_purchased)
SELECT item_Rank, category, item_purchased, total from item_counts
where item_Rank<=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, count(*) as repeat_buyers from customer_behavior
where previous_purchases >5 
GROUP BY subscription_status;

select * from customer_behavior limit 10;
-- Q10. What is the revenue contribution of each age group?
SELECT age_groups, sum(purchase_amount) as revenue from customer_behavior
GROUP BY age_groups
ORDER BY sum(purchase_amount) DESC;
-- This is total revenue for my References:
SELECT sum(purchase_amount) from customer_behavior




